version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: blogcraft
      POSTGRES_USER: blogcraft
      POSTGRES_PASSWORD: aK5dtkb1Z767HeAy6x73seWqMNpk62S1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: my_minio
    restart: always
    depends_on:
      - postgres
    command: server --console-address :9001 /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Y2rbs7yRaN9qNKcv8VuX7CP3VZz8rF5YmmWYqx35bG6dHsM8QU
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
